name: Bug Report
description: Report a bug or an issue.
title: "[BUG] "
labels: ["bug"]
projects: ["johnny-human/matmagia"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: title
    attributes:
      label: Title
      description: A short summary of the bug.
      placeholder: Bug summary
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug in detail.
      placeholder: Detailed description of the bug
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please list the steps to reproduce the bug.
      placeholder: Step-by-step reproduction steps
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened.
      placeholder: Actual behavior
    validations:
      required: true
